spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/local # DB URI
  batch:
    job:
      enabled: false # 애플리케이션 구동과 동시에 배치 작업 방지
      
# Movie Open Api 관련
movie:
  openApi:
    trending:
      uri: https://api.themoviedb.org/3
    apiKey : cbfa45007409cc068286bfeafd12a530
    
    
    
  